<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-S76SA9N" failures="1" tests="1" name="com.nexsoft.runner.NewEventRunner" time="32.388" errors="0" timestamp="2022-06-23T21:05:28 ICT" skipped="0">
  <testcase classname="com.nexsoft.runner.NewEventRunner" name="runScenario" time="32.388">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.nexsoft.definition.NewEventDefine.showUsers(NewEventDefine.java:131)
at âœ½.User showed in Main Activity(file:///D:/Project/Java/TestNG/ContactDiary/src/test/resources/NewEvent.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.nexsoft.runner.NewEventRunner -->
